### ISSUE TITLE
TypeError: log.notice is not a function

### ISSUE THREAD

**Issue by ProtocolNebula** [alexfernandez/nodecached#1]
If I try to execute `nodecached` i get the error:

```
TypeError: log.notice is not a function
    at Server.<anonymous> (/usr/lib/node_modules/nodecached/lib/server.js:94:8)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1382:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

If clone project and run `node lib/server.js`:
```
TypeError: log.debug is not a function
    at Object.exports.test (/home/developer/nodecached/lib/server.js:222:6)
    at Object.<anonymous> (/home/developer/nodecached/lib/server.js:235:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Possible fix:**
Replace in `server.js`:
```js
var log = new Log('info');
```

With:
```js
var log = Log;
```

This is a bad hotfix, but seems to work.
Maybe Log library has changed in the latest version.

**Comment by alexfernandez** [comment]
Care to send a PR?

**Comment by ProtocolNebula** [comment]
Ok, but first I try to fix correctly or replace Log library.

**Comment by alexfernandez** [comment]
I have just pinned the dep for the log library and tests seem to run fine, version 0.2.0. Care to try it?

**Comment by ProtocolNebula** [comment]
Now works!
Thanks.
